### ISSUE TITLE
S: compose and use

### ISSUE THREAD

**Issue by wli3** [ericgu/AnExerciseInCouplingDesRefWG#2]
https://github.com/ericgu/AnExerciseInCouplingDesRefWG/blob/master/StockTracker/Program.cs#L19

One line of code, it does 2 things, compose and use the composed object.

**Comment by wli3** [comment]
(nitpick a little, I did not find the majority(AnExerciseInCouplingDesRefWG\StockTracker\Form1.cs) of logic in the beginning)

**Comment by DanielOlewski** [comment]
How is that a problem with SRP? The way I read the code - the Program class is only responsible for starting the GUI application. No?

**Comment by wli3** [comment]
That's why I said it is kind of nitpick. But it does have 2 lines of config. Closing
