### ISSUE TITLE
Form1 shouldn't contain the logic to fetch stock

### ISSUE THREAD

**Issue by bastte** [ericgu/AnExerciseInCouplingDesRefWG#3]
https://github.com/ericgu/AnExerciseInCouplingDesRefWG/blob/master/StockTracker/Form1.cs#L28
Form1 shouldn't be aware of how stocks updates should be fetched

**Comment by DanielOlewski** [comment]
this applies to all stock operations, right? Form1 uses them, but shouldn't contain implementation for stock related operations?
