### ISSUE TITLE
Form1 shouldn't directly manage local stock cache

### ISSUE THREAD

**Issue by bastte** [ericgu/AnExerciseInCouplingDesRefWG#5]
It seems that we're caching some content to files.
This should be extracted to a dedicated object.

For example, https://github.com/ericgu/AnExerciseInCouplingDesRefWG/blob/master/StockTracker/Form1.cs#L91 and https://github.com/ericgu/AnExerciseInCouplingDesRefWG/blob/master/StockTracker/Form1.cs#L102 should be another component's responsibility

**Comment by valentiniliescu** [comment]
I agree, the loading and saving of stocks should be a separate concept - a repository.
